import type { Currency, FxRates, LedgerEvent, MemberId } from "@/lib/domain/balance-calculations";
import type { ProposalStatus } from "@/lib/domain/ledger-state-machine";
export type Proposal = { id: string; status: ProposalStatus; submitterId: MemberId; payload: Omit<LedgerEvent, "id" | "status"> };
export type Investment = { id: string; name: string; currency: Currency; openingQuantityMilli: number; openingCostMinor: number; valuations: { id: string; date: string; unitValueMinor: number; note: string }[] };
export type Goal = { id: string; name: string; targetMinor: number; currency: Currency };
export type Allocation = { id: string; goalId: string; source: "cash" | "investment"; sourceId?: string; amountMinor: number; currency: Currency; status: "active" | "released"; note: string };
export type Store = { active: MemberId; reporting: Currency; rates: FxRates; events: LedgerEvent[]; proposals: Proposal[]; investments: Investment[]; goals: Goal[]; allocations: Allocation[] };
export const members: Record<MemberId, string> = { guyan: "顾言", linzhixia: "林知夏" }; export const key = "joint-deposit-demo-store:v4";
export function seed(): Store { return { active: "guyan", reporting: "USD", rates: { USD: 1, CNY: 7.2, HKD: 7.8 }, events: [
 { id:"e1",type:"opening_balance",amountMinor:500000,currency:"USD",status:"posted",occurredAt:"2026-09-01",title:"共同账户期初余额" }, {id:"e2",type:"deposit",amountMinor:300000,currency:"USD",status:"posted",occurredAt:"2026-09-02",memberId:"guyan",title:"9月共同存入"}, {id:"e3",type:"expense",amountMinor:34268,currency:"USD",status:"posted",occurredAt:"2026-09-04",memberId:"linzhixia",category:"居住",title:"水电燃气"}, {id:"e4",type:"reimbursement",amountMinor:49900,currency:"USD",status:"posted",occurredAt:"2026-09-05",memberId:"linzhixia",category:"家居",title:"林知夏代付家居"}, {id:"e5",type:"investment_buy",amountMinor:100000,currency:"USD",status:"posted",occurredAt:"2026-09-03",memberId:"guyan",investmentId:"i1",quantityMilli:100000,unitPriceMinor:1000,title:"ETF 买入"}], proposals: [{id:"p1",status:"pending_approval",submitterId:"linzhixia",payload:{type:"expense",amountMinor:28650,currency:"USD",occurredAt:"2026-09-07",memberId:"linzhixia",category:"餐饮",title:"周末晚餐"}}], investments:[{id:"i1",name:"标普 500 ETF",currency:"USD",openingQuantityMilli:200000,openingCostMinor:200000,valuations:[{id:"v1",date:"2026-09-01",unitValueMinor:1050,note:"手工估值"},{id:"v2",date:"2026-09-07",unitValueMinor:1080,note:"最新净值"}]}], goals:[{id:"g1",name:"日本春季旅行",targetMinor:2000000,currency:"USD"}],allocations:[{id:"a1",goalId:"g1",source:"cash",amountMinor:150000,currency:"USD",status:"active",note:"旅行预留"}] }; }
export function load(): Store { try { const x=localStorage.getItem(key); return x ? JSON.parse(x) as Store : seed(); } catch{return seed();} } export const save=(x:Store)=>localStorage.setItem(key,JSON.stringify(x));
