"use client";
import { useRouter } from "next/navigation";
import { useMemo, useState } from "react";
import { Line, LineChart, ResponsiveContainer, Tooltip, XAxis, YAxis } from "recharts";
import { LogOut, Plus, RefreshCcw } from "lucide-react";
import { createClient } from "@/lib/supabase/client";

type Row = Record<string, unknown>;
type Props = { household: { id: string; name: string; reportingCurrency: string }; userId: string; entries: Row[]; proposals: Row[]; investments: Row[]; valuations: Row[]; members: Row[] };
const categories = ["日常生活", "餐饮", "居住", "家居", "交通", "旅行", "医疗健康", "礼物", "订阅服务", "宠物", "教育", "其他"];
const money = (minor: number, currency: string) => new Intl.NumberFormat("en-US", { style: "currency", currency }).format(minor / 100);

export default function AppClient({ household, userId, entries, proposals, investments, valuations }: Props) {
  const router = useRouter();
  const [tab, setTab] = useState("总览"); const [open, setOpen] = useState(false); const [kind, setKind] = useState("expense"); const [amount, setAmount] = useState(""); const [title, setTitle] = useState(""); const [category, setCategory] = useState(categories[0]); const [message, setMessage] = useState("");
  const posted = entries.filter((entry) => entry.status === "posted");
  const cash = posted.reduce((sum, entry) => { const amountMinor = Number(entry.amount_minor); return sum + (["opening_balance", "deposit", "expense_refund", "investment_sell", "dividend"].includes(String(entry.entry_type)) ? amountMinor : ["expense", "settlement", "investment_buy"].includes(String(entry.entry_type)) ? -amountMinor : 0); }, 0);
  const trend = useMemo(() => { const data = new Map<string, number>(); posted.forEach((entry) => { if (!["expense", "reimbursement", "expense_refund"].includes(String(entry.entry_type))) return; const date = String(entry.occurred_at); const current = data.get(date) || 0; data.set(date, current + (entry.entry_type === "expense_refund" ? -Number(entry.amount_minor) : Number(entry.amount_minor))); }); return [...data.entries()].map(([date, total]) => ({ date, total: total / 100 })); }, [posted]);
  async function submit(event: React.FormEvent) { event.preventDefault(); const amountMinor = Math.round(Number(amount) * 100); if (!title || amountMinor <= 0) return; const response = await fetch("/api/proposals", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ householdId: household.id, type: kind, amountMinor, currency: household.reportingCurrency, occurredAt: new Date().toISOString().slice(0, 10), title, category, idempotencyKey: crypto.randomUUID() }) }); const body = await response.json(); if (!response.ok) return setMessage(body.error || "提交失败"); setMessage("已提交给另一位成员审批。"); setOpen(false); setTitle(""); setAmount(""); window.location.reload(); }
  async function decide(id: string, approve: boolean) { const response = await fetch(`/api/proposals/${id}/decision`, { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ approve }) }); const body = await response.json(); if (!response.ok) return setMessage(body.error || "操作失败"); window.location.reload(); }
  async function logout() { await createClient().auth.signOut(); router.push("/login"); }
  return <main className="min-h-screen bg-[#f3f2ed] p-4 text-[#1d3029] md:p-7"><div className="mx-auto max-w-7xl rounded-3xl border bg-[#fbfaf6]"><header className="flex flex-wrap justify-between gap-3 border-b p-5"><div><p className="text-xs tracking-widest text-[#587064]">在线共同账本</p><h1 className="text-2xl font-bold">{household.name}</h1></div><div className="flex gap-2"><button onClick={() => setOpen(true)} className="rounded-xl bg-[#1f5243] px-4 py-2 text-sm font-bold text-white"><Plus size={16} className="inline"/> 新建记录</button><button onClick={() => window.location.reload()} className="rounded-xl border p-2" aria-label="刷新"><RefreshCcw size={17}/></button><button onClick={logout} className="rounded-xl border p-2" aria-label="退出登录"><LogOut size={17}/></button></div></header><nav className="flex gap-1 overflow-auto border-b p-2">{["总览", "审批中心", "流水", "投资"].map((item) => <button key={item} onClick={() => setTab(item)} className={`rounded-xl px-4 py-2 text-sm font-bold ${tab === item ? "bg-[#1f5243] text-white" : ""}`}>{item}</button>)}</nav><section className="p-5 md:p-7">{tab === "总览" && <Dashboard currency={household.reportingCurrency} cash={cash} entries={posted} trend={trend}/>} {tab === "审批中心" && <Approvals proposals={proposals} userId={userId} decide={decide} currency={household.reportingCurrency}/>} {tab === "流水" && <Ledger entries={posted} currency={household.reportingCurrency}/>} {tab === "投资" && <InvestmentList investments={investments} valuations={valuations} entries={posted} currency={household.reportingCurrency}/>}</section></div>{open && <Modal close={() => setOpen(false)} title="提交记录"><form onSubmit={submit} className="space-y-3"><select value={kind} onChange={(event) => setKind(event.target.value)}><option value="deposit">共同存入</option><option value="expense">共同账户消费</option><option value="reimbursement">成员代付共同消费</option><option value="settlement">报销付款</option><option value="investment_buy">投资买入</option><option value="investment_sell">投资卖出</option><option value="dividend">投资分红</option></select><input value={title} onChange={(event) => setTitle(event.target.value)} required placeholder="说明"/><input value={amount} onChange={(event) => setAmount(event.target.value)} type="number" step=".01" required placeholder={`金额（${household.reportingCurrency}）`}/>{["expense", "reimbursement"].includes(kind) && <select value={category} onChange={(event) => setCategory(event.target.value)}>{categories.map((item) => <option key={item}>{item}</option>)}</select>}<button className="w-full rounded-xl bg-[#1f5243] py-3 font-bold text-white">提交给对方审批</button></form></Modal>}{message && <div className="fixed bottom-6 left-1/2 -translate-x-1/2 rounded-xl bg-[#193d32] px-5 py-3 text-sm text-white">{message}</div>}</main>;
}
function Dashboard({ currency, cash, entries, trend }: { currency: string; cash: number; entries: Row[]; trend: { date: string; total: number }[] }) { const expense = entries.filter((entry) => ["expense", "reimbursement"].includes(String(entry.entry_type))).reduce((sum, entry) => sum + Number(entry.amount_minor), 0); const sankey = entries.filter((entry) => ["expense", "reimbursement"].includes(String(entry.entry_type))).reduce<Record<string, number>>((result, entry) => { const key = `${entry.entry_type === "expense" ? "共同账户支付" : "成员代付"} → ${entry.category || "其他"}`; result[key] = (result[key] || 0) + Number(entry.amount_minor); return result; }, {}); return <div className="space-y-6"><div className="grid gap-4 md:grid-cols-3"><Card label="共同现金" value={money(cash, currency)}/><Card label="累计共同消费" value={money(expense, currency)}/><Card label="已入账记录" value={`${entries.length} 笔`}/></div><div className="grid gap-6 xl:grid-cols-2"><section className="rounded-2xl border bg-white p-5"><b>消费趋势</b><p className="mt-1 text-xs text-gray-500">已审批消费，按发生日汇总。</p><div className="mt-4 h-72"><ResponsiveContainer><LineChart data={trend}><XAxis dataKey="date" tick={{ fontSize: 10 }}/><YAxis tick={{ fontSize: 10 }}/><Tooltip formatter={(value: number) => money(Math.round(value * 100), currency)}/><Line type="monotone" dataKey="total" stroke="#1f5243" strokeWidth={3}/></LineChart></ResponsiveContainer></div></section><section className="rounded-2xl border bg-white p-5"><b>消费资金取向</b><p className="mt-1 text-xs text-gray-500">支付来源 → 消费用途。</p><div className="mt-4 space-y-3">{Object.entries(sankey).length ? Object.entries(sankey).map(([key, amount]) => <div key={key}><div className="flex justify-between text-sm"><span>{key}</span><b>{money(amount, currency)}</b></div><div className="mt-1 h-2 rounded-full bg-[#edf0e9]"><div className="h-full rounded-full bg-[#1f5243]" style={{ width: `${Math.min(100, amount / Math.max(...Object.values(sankey)) * 100)}%` }}/></div></div>) : <p className="text-sm text-gray-500">暂无已审批消费。</p>}</div></section></div></div>; }
function Approvals({ proposals, userId, decide, currency }: { proposals: Row[]; userId: string; decide: (id: string, approve: boolean) => void; currency: string }) { return <div className="space-y-3">{proposals.length ? proposals.map((proposal) => { const payload = proposal.payload as Record<string, unknown>; const mine = proposal.submitter_id === userId; return <article key={String(proposal.id)} className="rounded-2xl border bg-white p-5"><div className="flex justify-between gap-3"><div><b>{String(payload.title)}</b><p className="mt-1 text-xs text-gray-500">{String(payload.type)} · {money(Number(payload.amountMinor || 0), String(payload.currency || currency))}</p></div><span className="rounded-full bg-amber-100 px-2 py-1 text-xs">{String(proposal.status)}</span></div>{["pending_approval", "overdue_pending"].includes(String(proposal.status)) && <div className="mt-4">{mine ? <span className="text-xs text-gray-500">你不能审批自己提交的记录。</span> : <><button onClick={() => decide(String(proposal.id), false)} className="mr-2 rounded-lg border px-3 py-2 text-sm">驳回</button><button onClick={() => decide(String(proposal.id), true)} className="rounded-lg bg-[#1f5243] px-3 py-2 text-sm text-white">批准并入账</button></>}</div>}</article>; }) : <p className="rounded-2xl border bg-white p-8 text-center text-sm text-gray-500">暂无审批记录。</p>}</div>; }
function Ledger({ entries, currency }: { entries: Row[]; currency: string }) { return <div className="overflow-hidden rounded-2xl border bg-white">{entries.map((entry) => <div key={String(entry.id)} className="flex justify-between gap-3 border-b p-4"><div><b>{String(entry.title)}</b><p className="mt-1 text-xs text-gray-500">{String(entry.occurred_at)} · {String(entry.entry_type)} · {String(entry.category || "")}</p></div><b>{money(Number(entry.amount_minor), String(entry.currency || currency))}</b></div>)}</div>; }
function InvestmentList({ investments, valuations, entries, currency }: { investments: Row[]; valuations: Row[]; entries: Row[]; currency: string }) { return <div className="space-y-4">{investments.length ? investments.map((investment) => { const records = entries.filter((entry) => entry.investment_id === investment.id); const latest = valuations.filter((value) => value.investment_id === investment.id).at(-1); return <article key={String(investment.id)} className="rounded-2xl border bg-white p-5"><h2 className="font-bold">{String(investment.name)}</h2><p className="mt-1 text-sm text-gray-500">{String(investment.currency)} · 最新估值 {latest ? money(Number(latest.unit_value_minor), String(latest.currency)) : "尚未录入"}</p><div className="mt-4 border-t pt-3 text-sm">{records.length ? records.map((record) => <p key={String(record.id)} className="mt-2">{String(record.occurred_at)} · {String(record.entry_type)} · {money(Number(record.amount_minor), String(record.currency || currency))}</p>) : "暂无已入账交易。"}</div></article>; }) : <p className="rounded-2xl border bg-white p-8 text-center text-sm text-gray-500">暂无投资标的。在线版将支持在此创建标的和提交买入、卖出、分红与估值审批。</p>}</div>; }
function Card({ label, value }: { label: string; value: string }) { return <div className="rounded-2xl border bg-white p-4"><p className="text-sm text-gray-500">{label}</p><b className="mt-3 block text-xl">{value}</b></div>; }
function Modal({ title, close, children }: { title: string; close: () => void; children: React.ReactNode }) { return <div className="fixed inset-0 z-50 grid place-items-center bg-black/40 p-4"><div className="w-full max-w-md rounded-2xl bg-white p-6"><div className="mb-4 flex justify-between"><b>{title}</b><button onClick={close}>×</button></div><div className="[&_input]:w-full [&_input]:rounded-xl [&_input]:border [&_input]:p-3 [&_select]:w-full [&_select]:rounded-xl [&_select]:border [&_select]:p-3">{children}</div></div></div>; }
