export type Currency = "USD" | "CNY" | "HKD";
export type MemberId = "guyan" | "linzhixia";
export type LedgerEventType = "opening_balance" | "deposit" | "expense" | "expense_refund" | "reimbursement" | "settlement" | "investment_buy" | "investment_sell" | "dividend";
export type FxRates = Record<Currency, number>;
export interface LedgerEvent { id: string; type: LedgerEventType; amountMinor: number; currency: Currency; status: "posted" | "voided"; occurredAt: string; memberId?: MemberId; category?: string; title?: string; investmentId?: string; quantityMilli?: number; unitPriceMinor?: number; }
export interface ProposalLike { status: string; payload: Pick<LedgerEvent, "type" | "amountMinor" | "currency" | "memberId">; }
export type ReimbursementSummary = { memberId: MemberId; paidMinor: number; reimbursedMinor: number; pendingMinor: number; availableMinor: number; currency: Currency };

export const currencies: Currency[] = ["USD", "CNY", "HKD"];
export const minorUnit = 100;
export const formatMoney = (amountMinor: number, currency: Currency) => new Intl.NumberFormat("en-US", { style: "currency", currency, minimumFractionDigits: 2 }).format(amountMinor / minorUnit);
export const postedEvents = (events: LedgerEvent[]) => events.filter((event) => event.status === "posted");
export function toReportingMinor(amountMinor: number, currency: Currency, reportingCurrency: Currency, rates: FxRates) { return Math.round(amountMinor / rates[currency] * rates[reportingCurrency]); }
export function cashImpact(event: LedgerEvent) { if (event.status !== "posted") return 0; return ["opening_balance", "deposit", "expense_refund", "investment_sell", "dividend"].includes(event.type) ? event.amountMinor : ["expense", "settlement", "investment_buy"].includes(event.type) ? -event.amountMinor : 0; }
export function cashBalance(events: LedgerEvent[], currency: Currency) { return events.filter((event) => event.currency === currency).reduce((sum, event) => sum + cashImpact(event), 0); }
export function cashBalanceReporting(events: LedgerEvent[], reporting: Currency, rates: FxRates) { return postedEvents(events).reduce((sum, event) => sum + toReportingMinor(cashImpact(event), event.currency, reporting, rates), 0); }
export function expenseTotalReporting(events: LedgerEvent[], reporting: Currency, rates: FxRates, prefix?: string) { return postedEvents(events).filter((event) => !prefix || event.occurredAt.startsWith(prefix)).reduce((sum, event) => sum + (["expense", "reimbursement"].includes(event.type) ? toReportingMinor(event.amountMinor, event.currency, reporting, rates) : event.type === "expense_refund" ? -toReportingMinor(event.amountMinor, event.currency, reporting, rates) : 0), 0); }
export function reimbursementSummary(events: LedgerEvent[], proposals: ProposalLike[] = []) { return (["guyan", "linzhixia"] as MemberId[]).flatMap((memberId) => currencies.map((currency) => { const rows = postedEvents(events).filter((event) => event.memberId === memberId && event.currency === currency); const paidMinor = rows.filter((event) => event.type === "reimbursement").reduce((sum, event) => sum + event.amountMinor, 0); const reimbursedMinor = rows.filter((event) => event.type === "settlement").reduce((sum, event) => sum + event.amountMinor, 0); const pendingMinor = proposals.filter((proposal) => ["pending_approval", "overdue_pending"].includes(proposal.status) && proposal.payload.type === "settlement" && proposal.payload.memberId === memberId && proposal.payload.currency === currency).reduce((sum, proposal) => sum + proposal.payload.amountMinor, 0); const confirmedOpen = Math.max(0, paidMinor - reimbursedMinor); return { memberId, currency, paidMinor, reimbursedMinor, pendingMinor, availableMinor: Math.max(0, confirmedOpen - pendingMinor) }; }).filter((item) => item.paidMinor || item.pendingMinor)); }
export function holdingMilli(events: LedgerEvent[], investmentId: string, openingQuantityMilli: number) { return postedEvents(events).filter((event) => event.investmentId === investmentId).reduce((sum, event) => sum + (event.type === "investment_buy" ? event.quantityMilli || 0 : event.type === "investment_sell" ? -(event.quantityMilli || 0) : 0), openingQuantityMilli); }
export const eventLabel = (type: LedgerEventType) => ({ opening_balance: "期初余额", deposit: "共同存入", expense: "共同账户消费", expense_refund: "共同消费退款", reimbursement: "成员代付共同消费", settlement: "报销付款", investment_buy: "投资买入", investment_sell: "投资卖出", dividend: "投资分红" })[type];
export function sumByCategory(events: LedgerEvent[], reporting: Currency, rates: FxRates, prefix?: string) { return postedEvents(events).reduce<Record<string, number>>((result, event) => { if (!(["expense", "reimbursement", "expense_refund"].includes(event.type)) || (prefix && !event.occurredAt.startsWith(prefix))) return result; const key = event.category || "其他"; result[key] = (result[key] || 0) + (event.type === "expense_refund" ? -1 : 1) * toReportingMinor(event.amountMinor, event.currency, reporting, rates); return result; }, {}); }
